export const dishesName = [
    'Biryani',
    'Stew',
    'Poutine',
    'Chicken tikka masala',
    'Eggs Benedict',
    'Pilaf',
    'Pizza',
    'Butter Chicken',
    'Pararha',
    'French toast',
    'Beef Stroganoff',
    'California roll',
    'Chaat',
    'Chutney',
    'Sushi',
    'Goulash',
    'Fettuccine Alfredo',
    'Samosa',
    'Poutine',
    'Chicken tikka masala',
    'Dosa',
    'Salisbury steak',
    'Pho',
    'Jalebi',
    'Sausages',
    'Lasagne',
    'Tandoori chicken',
    'Meatball',
    'Peking Duck',
    'Panipuri',
    'Pancakes',
    'Kebab',
    'Hamburger',
    'Dumplings',
    'Hot dog',
    'Nachos',
    'Fish soup',
    'Jambalaya',
    'Caesar salad',
    'Biryani',
    'Tacos'
]

export const cuisineTypesArr = ['american',
'asian',
'british',
'caribbean',
'central europe',
'chinese',
'eastern europe',
'french',
'greek',
'indian',
'italian',
'japanese',
'korean',
'kosher',
'mediterranean',
'mexican',
'middle eastern',
'nordic',
'south american',
'south east asian',
'world',
]
